"""add_device_session_columns

Revision ID: 8ed90c217304
Revises: 0001
Create Date: 2026-02-07 15:21:19.111303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ed90c217304'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('device_fingerprint', sa.String(length=64), nullable=True))
    op.add_column('devices', sa.Column('session_token', sa.String(length=64), nullable=True))
    op.add_column('devices', sa.Column('session_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_devices_session_token'), 'devices', ['session_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devices_session_token'), table_name='devices')
    op.drop_column('devices', 'session_expires_at')
    op.drop_column('devices', 'session_token')
    op.drop_column('devices', 'device_fingerprint')
    # ### end Alembic commands ###
